### ISSUE TITLE
Unable to take a screenshot and match on the first test run

### ISSUE THREAD

**Issue by NetanelH2** [FormidableLabs/react-native-owl#133]
When Im trying to run:
    const screen = await takeScreenshot('something')
    expect(screen).toMatchBaseline()
    
    I get this error again and again:
    
<img width="1022" alt="Screenshot 2022-12-04 at 18 18 12" src="https://user-images.githubusercontent.com/87550014/205502461-9f8c3b73-27af-4e7c-ac76-72321511b1d8.png">

Additional info:
Im able to press a button with testID in my app and moving forward to the next screen.

**Comment by muhammadkhan0009** [comment]
Hey @NetanelH2 
This is not the fix but setting jest timeout might help.
```
jest.setTimeout(50000);

describe('<Login/>', () => {
    it('takes a screenshot of the Login screen', async () => {
        await toExist('LoginWithEmailButton');
        await press('LoginWithEmailButton');
        const screen = await takeScreenshot('login');
        await toExist('goBackTestID');
        await press('goBackTestID');
        expect(screen).toMatchBaseline();
    });
});
```

**Comment by jwfwessels** [comment]
I've also noticed this happening occasionally on my side. It seems more prevalent on CI runs. I did a short investigation a few weeks ago and it seems to be caused by some race condition in the Websocket code. in some cases the websocket is expecting JSON responses (which represent the actions performed in tests as far as I can tell) but the initial connection message is plain text.

I did poke around briefly in the code but didn't have the time to dig into it. maybe one of the maintainers has an idea where the error could be.
